#!/usr/bin/env ruby

require_relative "hook_utils.rb"

##################################################
# prettier-ignore-start

ENABLED_CHECKERS = [
  Checker::Rubocop,
  Checker::Prettier,
  Checker::ESLint,
]

# prettier-ignore-end
##################################################

Runner::PreCommit.perform(ENABLED_CHECKERS)
