#!/usr/bin/env ruby

require_relative "linters.rb"

##################################################
# prettier-ignore-start

ENABLED_LINTERS = [
  Linter::Rubocop,
  Linter::Prettier,
  Linter::ESLint,
]

# prettier-ignore-end
##################################################

Linter::Runner.perform(ENABLED_LINTERS)
