[ -z "$PS1" ] && return

# when using bash-completion@2, different sources for git-prompt
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
if [ -d $(brew --prefix)/etc/bash_completion.d ]; then
  source $(brew --prefix)/etc/bash_completion.d/git-completion.bash

  # Set up dynamic prompt with git status
  source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
  GIT_PS1_SHOWCOLORHINTS=true
  GIT_PS1_SHOWDIRTYSTATE=true
  GIT_PS1_SHOWUNTRACKEDFILES=true
  GIT_PS1_SHOWCOLORHINTS=true
  GIT_PS1_DESCRIBE_STYLE="branch"
  GIT_PS1_SHOWUPSTREAM="auto git"
  PROMPT_COMMAND='__git_ps1 "\[\e]0;\u@\h | \w\a\][\u@\h \W" "]\$ "'
else
  PS1='\[\e]0;\u@\h | \w\a\][\u@\h \W]\$ '
fi

export HISTCONTROL=ignoredups:ignorespace
export HISTSIZE=-1 # unlimited history
export HISTFILESIZE=-1 # unlimited history
export EDITOR=vim
export VISUAL=vim
export GIT_EDITOR=vim
export SVN_EDITOR=vim
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
export INPUTRC=$HOME/.inputrc

# For BSD/MacOS, `ls` will show colors if CLICOLORS is set.
export CLICOLOR=1

# Enable vi mode for bash
set -o vi

# allow multiple terminals to write to history
shopt -s histappend

# automatically spelling correct when changing directory
shopt -s cdspell

shopt -s checkwinsize

export PATH="/usr/local/opt/libressl/bin:$PATH"
export PATH="$PATH:/usr/local/opt/mysql-client/bin"
export PATH="/usr/local/opt/redis@3.2/bin:$PATH"
[ -e /usr/local/heroku ] && export PATH=$PATH:/usr/local/heroku/bin
[ -f /Users/kyle/.travis/travis.sh ] && source /Users/kyle/.travis/travis.sh

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)"

export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init - --no-rehash)"

# Set pyenv env variables and add binaries to path.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - --no-rehash --path)"

# Add yarn global binaries to path.
export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"

[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"
export PATH=$HOME/Workspace/bin:$PATH

[ -f $HOME/.aliases ] && source $HOME/.aliases
[ -f $HOME/.work_aliases ] && source $HOME/.work_aliases

export DISABLE_SPRING=1

[ -f ~/.fzf.bash ] && source ~/.fzf.bash # install fzf extensions first

# fzf + rg configuration
if command -v fzf > /dev/null && command -v rg > /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-messages --glob "!.git/*"'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kyle/Workspace/bin/google-cloud-sdk/path.bash.inc' ]; then . '/Users/kyle/Workspace/bin/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kyle/Workspace/bin/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/kyle/Workspace/bin/google-cloud-sdk/completion.bash.inc'; fi
