#!/usr/bin/env ruby

def red(string)
  "\e[31m#{string}\e[0m"
end

def print_status(status)
  puts
  puts("=" * 50)
  puts red(status)
  puts("=" * 50)
  puts
end

files = `git diff --cached --name-only --diff-filter=ACM -- *.{rb,js,jsx,ts}`.split("\n")
exit(0) if files.empty?

has_errors = false

if (rb_files = files.select { |f| f.match(/.rb$/) }).any?
  print_status("Auto-correcting rubocop...")
  has_errors ||= !system("rubocop --format simple --auto-correct #{rb_files.join(" ")}")
end

if (js_files = files.select { |f| f.match(/.(?:js|jsx|ts)$/) }).any?
  targets = js_files.join(" ")

  if !system("yarn run --silent prettier --list-different #{targets} > /dev/null 2>&1")
    print_status("Auto-correcting prettier...")
    has_errors = true
    system("yarn run --silent prettier --write #{targets}")
  end

  if !(system("yarn run --silent eslint #{targets} > /dev/null 2>&1"))
    print_status("Auto-correcting eslint...")
    has_errors = true
    system("yarn run --silent eslint --fix #{targets}")
  end
end

if has_errors
  print_status("Errors detected, aborting commit...")
  exit(1)
end

exit(0)
